### ISSUE TITLE
Where did HTML/HAL go?

### ISSUE THREAD

**Issue by estebistec** [core-api/python-client#87]
It appears some of the documented codecs have gone from the codebase. Did HAL and HTML move somewhere else? These are currently highlight somewhat prominently in the docs.

**Comment by tomchristie** [comment]
In order to keep everything modular, and the core package nice and well defined, I've split these all out into separate packages. I've just been updating the documentation on coreapi.org now, so if you take a look you'll see those linked in. (I'd temporarily put them under the `encode` organisation, but realised that was an odd choice, so they're now under this org)

**Comment by tomchristie** [comment]
Note that the command line client is also a separately installable package, too.
I'll be working towards more complete documentation for both the client lib and the command line client over the next few weeks.

**Comment by estebistec** [comment]
Gotcha. I must looked just too soon. Thanks!
